CREATE TABLE USUARIO (
    ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    USER VARCHAR(150) NOT NULL,
    PASSWORD VARCHAR(150) NOT NULL,
    ROLE VARCHAR(50) NOT NULL
);

CREATE TABLE EMPREGADO_RH (
    ID_EMPREGADO_RH INT PRIMARY KEY AUTO_INCREMENT,
	/*INFO. BASICO*/
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
	SEXO VARCHAR(1)  NOT NULL,
    IDADE VARCHAR(2) NOT NULL,
	DATA_NASCIMENTO DATETIME NOT NULL,
    NACIONALIDADE VARCHAR(100) NOT NULL,
    NOME_PAI VARCHAR(100),
    NOME_MAE VARCHAR(100) NOT NULL,
    QUANTIDADE_FILHOS INT NOT NULL,
    /*ENDERECO*/
    CEP VARCHAR(10) NOT NULL,
	PAIS VARCHAR(100) NOT NULL,
    ESTADO VARCHAR(2) NOT NULL,
    CIDADE VARCHAR(100) NOT NULL,
    RUA VARCHAR(100) NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
	/*CONTATO*/
    EMAIL_PESSOAL VARCHAR(100),
    EMAIL_PROFISSIONAL VARCHAR(100),
    CONTATO VARCHAR(15) NOT NULL,
    CONTATO_SECONDARIO VARCHAR(15),
	/*INFO. CRITICO*/
    REGISTRO_NASCIMENTO VARCHAR(32) NOT NULL,
    CIDADE_NASCIMENTO VARCHAR(100) NOT NULL,
    REGISTRO_CASAMENTO VARCHAR(32) NOT NULL,
    
    CARTEIRA_MOTORISTA VARCHAR(11),
    CATEGORIA VARCHAR(3),
    
    TITULO_ELEITORAL VARCHAR(11) NOT NULL,
    ZONA VARCHAR(4) NOT NULL,
    SECAO VARCHAR(4) NOT NULL,
    
    NOME_FACULDADE VARCHAR(100),
    MATRICULA_FACULDADE VARCHAR(40),
    
    PIS_PASEP VARCHAR(11) NOT NULL,
    NUMERO_CARTEIRA_TRABALHO VARCHAR(8) NOT NULL,
    SERIE_CARTEIRA_TRABALHO VARCHAR(4) NOT NULL,
    UF_CARTEIRA_TRABALHO VARCHAR(2) NOT NULL,
    
    CARGO VARCHAR(100) NOT NULL,
    SALARIO DECIMAL(10,2) NOT NULL,
    DATA_ENTRADA DATETIME NOT NULL,
    DATA_DESLIGAMENTO DATETIME
);

CREATE TABLE FILHO_EMPREGADO_RH (
	ID_FILHO_EMPREGADO_RH INTEGER PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(80) NOT NULL,
	IDADE VARCHAR(2) NOT NULL,
	REGISTRO_NASCIMENTO VARCHAR(32) NOT NULL,
	DATA_NASCIMENTO DATETIME NOT NULL
);

CREATE TABLE EMPREGADO (
	ID_EMPREGADO INT PRIMARY KEY AUTO_INCREMENT,
	/*INFO. BASICO*/
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
	SEXO VARCHAR(1)  NOT NULL,
    IDADE VARCHAR(2) NOT NULL,
	DATA_NASCIMENTO DATETIME NOT NULL,
    NACIONALIDADE VARCHAR(100) NOT NULL,
    NOME_PAI VARCHAR(100),
    NOME_MAE VARCHAR(100) NOT NULL,
    QUANTIDADE_FILHOS INT NOT NULL,
    /*ENDERECO*/
    CEP VARCHAR(10) NOT NULL,
	PAIS VARCHAR(100) NOT NULL,
    ESTADO VARCHAR(2) NOT NULL,
    CIDADE VARCHAR(100) NOT NULL,
    RUA VARCHAR(100) NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
	/*CONTATO*/
    EMAIL_PESSOAL VARCHAR(100),
    EMAIL_PROFISSIONAL VARCHAR(100),
    CONTATO VARCHAR(15) NOT NULL,
    CONTATO_SECONDARIO VARCHAR(15),
	/*INFO. CRITICO*/
    REGISTRO_NASCIMENTO VARCHAR(32) NOT NULL,
    CIDADE_NASCIMENTO VARCHAR(100) NOT NULL,
    REGISTRO_CASAMENTO VARCHAR(32) NOT NULL,
    
    CARTEIRA_MOTORISTA VARCHAR(11),
    CATEGORIA VARCHAR(3),
    
    TITULO_ELEITORAL VARCHAR(11) NOT NULL,
    ZONA VARCHAR(4) NOT NULL,
    SECAO VARCHAR(4) NOT NULL,
    
    NOME_FACULDADE VARCHAR(100),
    MATRICULA_FACULDADE VARCHAR(40),
    
    PIS_PASEP VARCHAR(11) NOT NULL,
    NUMERO_CARTEIRA_TRABALHO VARCHAR(8) NOT NULL,
    SERIE_CARTEIRA_TRABALHO VARCHAR(4) NOT NULL,
    UF_CARTEIRA_TRABALHO VARCHAR(2) NOT NULL,
    
    CARGO VARCHAR(100) NOT NULL,
    SALARIO DECIMAL(10,2) NOT NULL,
    DATA_ENTRADA DATETIME NOT NULL,
    DATA_DESLIGAMENTO DATETIME
);

CREATE TABLE FILHO (
	ID_FILHO INTEGER PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(80) NOT NULL,
	IDADE VARCHAR(2) NOT NULL,
	REGISTRO_NASCIMENTO VARCHAR(32) NOT NULL,
	DATA_NASCIMENTO DATETIME NOT NULL
);

CREATE TABLE EMPRESA (
	ID_EMPRESA INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(150) NOT NULL,
    CNPJ VARCHAR(14) NOT NULL,
    CEP VARCHAR(10) NOT NULL,
    
	PAIS VARCHAR(80) NOT NULL,
	ESTADO VARCHAR(2) NOT NULL,
	CIDADE VARCHAR(80) NOT NULL,
    RUA VARCHAR(80) NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,

    CONTATO_CORPORATIVO VARCHAR(15) NOT NULL,
	EMAIL_CORPORATIVO VARCHAR(80) NOT NULL
);

CREATE TABLE OPORTUNIDADE_INTERNA(
    ID_OPORTUNIDADE_INTERNA INT PRIMARY KEY AUTO_INCREMENT,
    DATA_PUBLICADO DATETIME NOT NULL,
    CARGO VARCHAR(200) NOT NULL,
    REQUISITOS VARCHAR(500) NOT NULL,
    OBSERVACAO VARCHAR(500)
);

CREATE TABLE OPORTUNIDADE(
    ID_OPORTUNIDADE INT PRIMARY KEY AUTO_INCREMENT,
    DATA_PUBLICADO DATETIME NOT NULL,
    CARGO VARCHAR(200) NOT NULL,
    REQUISITOS VARCHAR(500) NOT NULL,
    OBSERVACAO VARCHAR(500)
);