CREATE TABLE EMPRESA_EMPREGADO (
	ID_EMPRESA_EMPREGADO INTEGER PRIMARY KEY AUTO_INCREMENT,
	ID_EMPREGADO INTEGER NOT NULL,
	ID_EMPRESA INTEGER NOT NULL,
	FOREIGN KEY(ID_EMPREGADO) REFERENCES EMPREGADO (ID_EMPREGADO),
	FOREIGN KEY(ID_EMPRESA) REFERENCES EMPRESA(ID_EMPRESA)
);

CREATE TABLE EMPREGADO_FILHO (
	ID_EMPREGADO_FILHO INTEGER PRIMARY KEY AUTO_INCREMENT
	ID_EMPREGADO INTEGER NOT NULL,
	ID_FILHO INTEGER NOT NULL,
	FOREIGN KEY(ID_EMPREGADO) REFERENCES EMPREGADO (ID_EMPREGADO),
	FOREIGN KEY(ID_FILHO) REFERENCES FILHO(ID_FILHO)
);

CREATE TABLE EMPREGADO_RH_FILHOS (
	ID_EMPREGADO_RH_FILHO INTEGER PRIMARY KEY AUTO_INCREMENT,
	ID_EMPREGADO_RH INTEGER NOT NULL,
	ID_FILHO_EMPREGADO_RH INTEGER NOT NULL,
	FOREIGN KEY(ID_EMPREGADO_RH) REFERENCES EMPREGADO_RH (ID_EMPREGADO_RH),
	FOREIGN KEY(ID_FILHO_EMPREGADO_RH) REFERENCES FILHO_EMPREGADO_RH(ID_FILHO_EMPREGADO_RH)
);

CREATE TABLE EMPRESA_OPORTUNIDADE(
	ID_EMPRESA_OPORTUNIDADE INTEGER PRIMARY KEY AUTO_INCREMENT,
	ID_OPORTUNIDADE INTEGER NOT NULL,
	ID_EMPRESA INTEGER NOT NULL,
	FOREIGN KEY(ID_OPORTUNIDADE) REFERENCES OPORTUNIDADE(ID_OPORTUNIDADES),
	FOREIGN KEY(ID_EMPRESA) REFERENCES EMPRESA(ID_EMPRESA)
);